In [638]:
import numpy as np
import pandas as pd
import matplotlib as plt
df = pd.read_csv(r"student_depression_dataset.csv",index_col= 0,header = 0 )

In [639]:
print(df.shape)

(27902, 17)


In [640]:
print(df.describe())

                Age  Academic Pressure  Work Pressure          CGPA  \
count  27902.000000       27902.000000   27902.000000  27902.000000   
mean      25.822056           3.141244       0.000430      7.656045   
std        4.905770           1.381450       0.043991      1.470714   
min       18.000000           0.000000       0.000000      0.000000   
25%       21.000000           2.000000       0.000000      6.290000   
50%       25.000000           3.000000       0.000000      7.770000   
75%       30.000000           4.000000       0.000000      8.920000   
max       59.000000           5.000000       5.000000     10.000000   

       Study Satisfaction  Job Satisfaction  Work/Study Hours    Depression  
count        27902.000000      27902.000000      27902.000000  27902.000000  
mean             2.943839          0.000681          7.157014      0.585514  
std              1.361124          0.044394          3.707579      0.492642  
min              0.000000          0.000000     

In [641]:
df['Gender'].nunique()

2

In [642]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [643]:
df['Gender'].value_counts()

Gender
Male      15548
Female    12354
Name: count, dtype: int64

In [644]:
df['Age'].nunique()

34

In [645]:
df['Age'].unique()

array([19, 33, 24, 31, 28, 25, 29, 30, 27, 20, 23, 18, 21, 22, 34, 32, 26,
       39, 35, 42, 36, 58, 49, 38, 51, 44, 43, 46, 59, 54, 48, 56, 37, 41])

In [646]:
df['Age'].value_counts()

Age
24    2258
20    2237
28    2133
29    1950
33    1893
25    1784
21    1726
23    1645
18    1587
19    1561
34    1468
27    1462
31    1427
32    1262
22    1160
26    1155
30    1145
35      10
38       8
36       7
42       4
48       3
39       3
43       2
46       2
37       2
49       1
51       1
44       1
59       1
54       1
58       1
56       1
41       1
Name: count, dtype: int64

In [647]:
df['City'].nunique()

51

In [648]:
df['City'].unique()

array(['Delhi', 'Visakhapatnam', 'Bangalore', 'Srinagar', 'Varanasi',
       'Jaipur', 'Pune', 'Thane', 'Chennai', 'Nagpur', 'Nashik',
       'Vadodara', 'Kalyan', 'Rajkot', 'Ahmedabad', 'Kolkata', 'Mumbai',
       'Lucknow', 'Indore', 'Surat', 'Ludhiana', 'Bhopal', 'Meerut',
       'Agra', 'Ghaziabad', 'Hyderabad', 'Vasai-Virar', 'Kanpur', 'Patna',
       'Faridabad', 'Saanvi', 'M.Tech', 'Bhavna', 'City', '3',
       "'Less than 5 Kalyan'", 'Mira', 'Harsha', 'Vaanya', 'Gaurav',
       'Harsh', 'Reyansh', 'Kibara', 'Rashi', 'ME', 'M.Com', 'Nalyan',
       'Mihir', 'Nalini', 'Nandini', 'Khaziabad'], dtype=object)

In [649]:
df['City'].value_counts()

City
Kalyan                  1570
Srinagar                1372
Hyderabad               1340
Vasai-Virar             1290
Lucknow                 1155
Thane                   1139
Ludhiana                1111
Agra                    1094
Surat                   1078
Kolkata                 1066
Jaipur                  1036
Patna                   1007
Visakhapatnam            969
Pune                     968
Ahmedabad                951
Bhopal                   934
Chennai                  885
Meerut                   825
Rajkot                   816
Delhi                    770
Bangalore                767
Ghaziabad                745
Mumbai                   699
Vadodara                 694
Varanasi                 685
Nagpur                   651
Indore                   643
Kanpur                   609
Nashik                   547
Faridabad                461
Harsha                     2
Saanvi                     2
Bhavna                     2
City                       2
ME       

In [650]:
def remove_unwanted_cities(x:str):
    unwanted = ['Saanvi', 'M.Tech', 'Bhavna', 'City', '3',
       "'Less than 5 Kalyan'", 'Mira', 'Harsha', 'Vaanya', 'Gaurav',
       'Harsh', 'Reyansh', 'Kibara', 'Rashi', 'ME', 'M.Com', 'Nalyan',
       'Mihir', 'Nalini', 'Nandini']
    if x in unwanted:
        return pd.NA
    elif x == 'Khaziabad' :
        return 'Ghaziabad'
    else:
        return x
df['City'] = df['City'].apply(remove_unwanted_cities)


In [651]:
df['Profession'].nunique()

14

In [652]:
df['Profession'].unique()

array(['Student', "'Civil Engineer'", 'Architect', "'UX/UI Designer'",
       "'Digital Marketer'", "'Content Writer'",
       "'Educational Consultant'", 'Teacher', 'Manager', 'Chef', 'Doctor',
       'Lawyer', 'Entrepreneur', 'Pharmacist'], dtype=object)

In [653]:
df['Profession'].value_counts()

Profession
Student                     27871
Architect                       8
Teacher                         6
'Digital Marketer'              3
'Content Writer'                2
Chef                            2
Doctor                          2
Pharmacist                      2
'Civil Engineer'                1
'UX/UI Designer'                1
'Educational Consultant'        1
Manager                         1
Lawyer                          1
Entrepreneur                    1
Name: count, dtype: int64

In [654]:
df['Academic Pressure'].nunique()

6

In [655]:
df['Academic Pressure'].unique()

array([4, 5, 2, 3, 1, 0])

In [656]:
df['Academic Pressure'].value_counts()

Academic Pressure
3    7462
5    6296
4    5156
1    4801
2    4178
0       9
Name: count, dtype: int64

In [657]:
df['Work Pressure'].nunique()

3

In [658]:
df['Work Pressure'].unique()

array([0, 5, 2])

In [659]:
df['Work Pressure'].value_counts()

Work Pressure
0    27899
5        2
2        1
Name: count, dtype: int64

In [660]:
df['CGPA'].nunique()

332

In [661]:
df['CGPA'].unique()

array([ 6.    ,  8.97  ,  5.9   ,  7.03  ,  5.59  ,  8.13  ,  5.7   ,
        9.54  ,  8.04  ,  9.79  ,  8.38  ,  6.1   ,  7.04  ,  8.52  ,
        5.64  ,  8.58  ,  6.51  ,  7.25  ,  7.83  ,  9.93  ,  8.74  ,
        6.73  ,  5.57  ,  8.59  ,  7.1   ,  6.08  ,  5.74  ,  9.86  ,
        6.7   ,  6.21  ,  5.87  ,  6.37  ,  9.72  ,  5.88  ,  9.56  ,
        6.99  ,  5.24  ,  9.21  ,  7.85  ,  6.95  ,  5.86  ,  7.92  ,
        9.66  ,  8.94  ,  9.71  ,  7.87  ,  5.6   ,  7.9   ,  5.46  ,
        6.79  ,  8.7   ,  7.38  ,  8.5   ,  7.09  ,  9.82  ,  8.89  ,
        7.94  ,  9.11  ,  6.75  ,  7.53  ,  9.49  ,  9.01  ,  7.64  ,
        5.27  ,  9.44  ,  5.75  ,  7.51  ,  9.05  ,  6.38  ,  8.95  ,
        9.88  ,  5.32  ,  6.27  ,  7.7   ,  8.1   ,  9.59  ,  8.96  ,
        5.51  ,  7.43  ,  8.79  ,  9.95  ,  5.37  ,  6.86  ,  8.32  ,
        9.74  ,  5.66  ,  7.48  ,  8.23  ,  8.81  ,  6.03  ,  5.56  ,
        5.68  ,  5.14  ,  7.61  ,  6.17  ,  8.17  ,  9.87  ,  8.75  ,
        6.16  ,  9.5

In [662]:
df['CGPA'].value_counts()

CGPA
8.04    821
9.96    425
5.74    410
8.95    371
9.21    343
       ... 
7.65      1
6.77      1
8.26      1
7.23      1
6.09      1
Name: count, Length: 332, dtype: int64

In [663]:
df['Study Satisfaction'].nunique()

6

In [664]:
df['Study Satisfaction'].unique()

array([3, 2, 5, 4, 1, 0])

In [665]:
df['Study Satisfaction'].value_counts()

Study Satisfaction
4    6359
2    5838
3    5822
1    5451
5    4422
0      10
Name: count, dtype: int64

In [666]:
df['Job Satisfaction'].nunique()

5

In [667]:
df['Job Satisfaction'].unique()

array([0, 3, 4, 2, 1])

In [668]:
df['Job Satisfaction'].value_counts()

Job Satisfaction
0    27894
2        3
4        2
1        2
3        1
Name: count, dtype: int64

In [669]:
df['Sleep Duration'].nunique()

6

In [670]:
df['Sleep Duration'].unique()

array(["'6-7 hours'", "'5-6 hours'", "'Less than 5 hours'", "'7-8 hours'",
       "'More than 8 hours'", 'Others'], dtype=object)

In [671]:
df['Sleep Duration'].value_counts()

Sleep Duration
'Less than 5 hours'    8310
'7-8 hours'            7346
'5-6 hours'            6183
'More than 8 hours'    6044
Others                   18
'6-7 hours'               1
Name: count, dtype: int64

In [672]:
'''use only if integer value of sleep hours is needed'''
# def sleep_fix(x: str):
#     encounters = []
#     temp = ""
#     for y in range(len(x)):
#         if x[y].isdigit():
#             if len(temp) > 0:
#                 temp = temp + x[y]
#                 encounters.append(str(temp))
#             else:
#                 temp = x[y]
            
#         else :
#             if len(temp) > 0 :
#                 encounters.append(str(temp))
#             temp = ""
#     if len(encounters) > 0 :
#         return max(encounters)
#     else:
#         return ""
# df['Sleep Duration'] = df['Sleep Duration'].apply(sleep_fix)

'use only if integer value of sleep hours is needed'

In [673]:
df['Dietary Habits'].nunique()

4

In [674]:
df['Dietary Habits'].unique()

array(['Moderate', 'Healthy', 'Unhealthy', 'Others'], dtype=object)

In [675]:
df['Dietary Habits'].value_counts()

Dietary Habits
Unhealthy    10317
Moderate      9922
Healthy       7651
Others          12
Name: count, dtype: int64

In [676]:
df['Degree'].nunique()

29

In [677]:
df['Degree'].unique()

array(['B.com', 'B.Pharm', 'BSc', 'BA', 'BCA', 'M.Tech', 'PhD',
       "'Class 12'", 'B.Ed', 'LLB', 'BE', 'M.Ed', 'MSc', 'BHM', 'M.Pharm',
       'MCA', 'MA', 'B.Com', 'MD', 'MBA', 'MBBS', 'M.Com', 'B.Arch',
       'LLM', 'B.Tech', 'BBA', 'ME', 'MHM', 'Others'], dtype=object)

In [678]:
df['Degree'].value_counts()

Degree
'Class 12'    6080
B.Ed          1867
B.Com         1506
B.Arch        1478
BCA           1433
MSc           1190
B.Tech        1152
MCA           1044
M.Tech        1022
BHM            925
BSc            888
M.Ed           821
B.Pharm        810
M.Com          734
MBBS           696
BBA            696
LLB            671
BE             613
BA             600
M.Pharm        582
MD             572
MBA            562
MA             544
PhD            522
LLM            482
MHM            191
ME             185
Others          35
B.com            1
Name: count, dtype: int64

In [679]:
df['Have you ever had suicidal thoughts ?'].nunique()

2

In [680]:
df['Have you ever had suicidal thoughts ?'].unique()

array(['Yes', 'No'], dtype=object)

In [681]:
df['Have you ever had suicidal thoughts ?'].value_counts()

Have you ever had suicidal thoughts ?
Yes    17657
No     10245
Name: count, dtype: int64

In [682]:
df['Work/Study Hours'].nunique()

13

In [683]:
df['Work/Study Hours'].unique()

array([ 8,  3,  9,  4,  1,  0, 12,  2, 11, 10,  6,  5,  7])

In [684]:
df['Work/Study Hours'].value_counts()

Work/Study Hours
10    4234
12    3172
11    2892
8     2510
6     2247
9     2026
7     2001
0     1700
4     1614
2     1590
3     1470
5     1296
1     1150
Name: count, dtype: int64

In [685]:
df['Financial Stress'].nunique()

6

In [686]:
df['Financial Stress'].unique()

array(['4', '1', '2', '5', '3', '?'], dtype=object)

In [687]:
df['Financial Stress'].value_counts()

Financial Stress
5    6715
4    5776
3    5226
1    5121
2    5061
?       3
Name: count, dtype: int64

In [688]:
df['Financial Stress'] = df['Financial Stress'].apply(lambda x : pd.NA if x == '?' else x)

In [689]:
df['Family History of Mental Illness'].nunique()

2

In [690]:
df['Family History of Mental Illness'].unique()

array(['No', 'Yes'], dtype=object)

In [691]:
df['Family History of Mental Illness'].value_counts()

Family History of Mental Illness
No     14399
Yes    13503
Name: count, dtype: int64

In [692]:
df['Depression'].nunique()

2

In [693]:
df['Depression'].unique()

array([1, 0])

In [694]:
df['Depression'].value_counts()

Depression
1    16337
0    11565
Name: count, dtype: int64